export { AlcError, checkSymbol, withCheck, CROCKFORD, HEX, OCTAL } from './codec.ts';
export {
  FRAMES,
  ENABLED_FRAMES,
  parse,
  format,
  isValid,
  parent,
  ancestors,
  children,
  contains,
  normalizeCovering,
  canonicalLevel,
  type Address,
} from './address.ts';
export { locate, encodeBody, encodeBrainVolume, type TemplateSet } from './locate.ts';
export {
  overlaps,
  coveringsIntersect,
  coveringIntersection,
  samePlace,
  recommendedDigits,
  type SamePlaceResult,
  type SamePlaceOptions,
} from './compare.ts';
export {
  EMPTY_COVERING,
  covering,
  isCovering,
  isEmptyCovering,
  coveringUnion,
  coveringIntersect,
  coveringsOverlap,
  coveringContains,
  coveringOverlapsAddress,
  relativeMeasure,
  coveringMeasureWithin,
  coveringRollUp,
  coveringFromRegion,
  coveringFromPointsMm,
  bodyFrameRoots,
  brainVolumeFrameRoots,
  ballRegion,
  coveringsSamePlace,
  type Covering,
  type CellClassification,
  type CellRegion,
  type RegionCoveringOptions,
  type PointCoveringResult,
  type SamenessRegime,
  type CoveringSamePlaceResult,
} from './covering.ts';
export {
  EMPTY_SCAN,
  prefixRange,
  descendantScan,
  ancestorScan,
  overlapScan,
  coveringScan,
  renderScan,
  scanSorted,
  type PrefixRange,
  type ScanPlan,
  type SqlDialect,
  type RenderOptions,
  type ParameterisedQuery,
} from './query.ts';
export {
  buildNameIndex,
  resolve,
  resolveCovering,
  structureCovering,
  containingStructures,
  findStructures,
  frameRootOf,
  coveringMeasure,
  type StructureRef,
  type NameIndexEntry,
  type NameIndexInput,
  type NameIndex,
  type ResolvedStructure,
  type Resolution,
  type CoveringResolution,
  type ResolveOptions,
} from './resolve.ts';
export {
  toReadable,
  toSpoken,
  fromReadable,
  isReadable,
  describe,
  frameSummary,
  frameSummaries,
  type AddressPart,
  type AddressDescription,
} from './translate.ts';
export {
  BD,
  VERTEBRAL_LEVELS,
  ANOMALOUS_LEVELS,
  ADDRESSABLE_LEVELS,
  levelClass,
  auditBodyTemplate,
  auditBodyTemplateWorstCase,
  levelsClaiming,
  scanBodyTemplateFolds,
  formatFoldScan,
  spineGeometry,
  type TemplateAudit,
  type LevelAudit,
  type FoldScan,
  type FoldScanOptions,
  type FoldSite,
  bodyCellBox,
  bodyEncodeLocal,
  bodyLocalToMm,
  bodyMmToLocal,
  bodyLocate,
  clockToTurnInterval,
  turnToClock,
  type BodyTemplate,
  type VertebralSlab,
  type LocalBodyCoords,
} from './frames/bodySpine.ts';
export {
  BV,
  bvCellBox,
  bvEncodeLocal,
  bvLocalToMm,
  bvMmToLocal,
  bvLocate,
  type BrainVolumeTemplate,
} from './frames/brainVolume.ts';
export {
  BR,
  brPixel,
  brDigits,
  brEncodeSphere,
  brDecodeSphere,
  brParentDigits,
  brChildDigits,
  cellAreaMm2,
  digitsToOrder,
  orderToDigits,
} from './frames/brainSurface.ts';
export * as healpix from './healpix.ts';
export type { Vec3, Hemisphere, Homology, Located, LocateFlags, FrameDescriptor } from './types.ts';
