/**
 * Regenerates docs/alc-1-admissibility.md.
 *
 *   node --experimental-strip-types test/admissibility.sweep.mjs > ../../docs/alc-1-admissibility.md
 *
 * Everything in that document comes from here, so no number in it is a claim
 * somebody typed by hand.
 */

import {
  auditBodyTemplate,
  auditBodyTemplateWorstCase,
  bodyLocalToMm,
  bodyMmToLocal,
  spineGeometry,
} from '../src/index.ts';
import {
  ADULT_P50,
  PRESETS,
  ADULT_P50_SPLIT_SACRUM,
  buildAnatomicalBodyTemplate,
} from '../src/testing/anatomicalTemplates.ts';
import { measureRoundTrip } from '../src/testing/admissibilityProbe.ts';

const out = [];
const line = (s = '') => out.push(s);

const GIRTHS = [0.7, 0.85, 1.0, 1.15, 1.3, 1.45, 1.6, 1.75];

function roundTrips(t, level, u, az, r) {
  try {
    const mm = bodyLocalToMm(t, { level, u, t: az, r });
    const b = bodyMmToLocal(t, mm);
    let dt = Math.abs(b.local.t - az);
    dt = Math.min(dt, 1 - dt);
    return b.local.level === level && Math.abs(b.local.u - u) < 1e-6 && dt < 1e-6 && Math.abs(b.local.r - r) < 1e-6;
  } catch {
    return false;
  }
}

/** Volume-weighted fraction of the body where the frame is ambiguous. */
function ambiguousVolumeFraction(t) {
  const g = spineGeometry(t);
  let bad = 0;
  let all = 0;
  t.slabs.forEach((slab, i) => {
    const n = slab.surfaceRadiiMm.length;
    for (let a = 0; a < 48; a += 1) {
      const az = (a + 0.5) / 48;
      const rho = slab.surfaceRadiiMm[Math.round(az * n) % n];
      for (let k = 0; k < 24; k += 1) {
        const r = (k + 0.5) / 24;
        const w = r * rho * rho * g.lens[i];
        all += w;
        if (!roundTrips(t, slab.label, 0.5, az, r)) bad += w;
      }
    }
  });
  return bad / all;
}

const worstOf = (audit) => audit.levels.reduce((m, l) => (l.utilisation > m.utilisation ? l : m), audit.levels[0]);

line('# ALC-1 body template admissibility — measured report');
line();
line('Generated by `packages/alc/test/admissibility.sweep.mjs`. Every number below');
line('is computed, not asserted. Regenerate it whenever the frame or a template');
line('changes.');
line();
line('The `BD` frame is a tubular neighbourhood of the spinal curve, so it folds');
line('where the body is thicker than the distance at which a level\'s two bounding');
line('bisector planes meet. Beyond that fold two different addresses denote the');
line('same millimetre point, and `encode(locate(a))` stops returning `a`.');
line();
line('**Utilisation** below is `bodyRadius / foldRadius` at the worst azimuth of');
line('the worst level. Under 1 is admissible; 1 or more means part of the body is');
line('ambiguous.');
line();

// ---------------------------------------------------------------------------
line('## 1. The presets');
line();
line('| template | worst level | azimuth | utilisation | fold radius | body radius | round-trip failures | ambiguous volume |');
line('| --- | --- | --- | --- | --- | --- | --- | --- |');
for (const params of [...PRESETS, ADULT_P50_SPLIT_SACRUM]) {
  const t = buildAnatomicalBodyTemplate(params);
  const w = worstOf(auditBodyTemplate(t));
  const probe = measureRoundTrip(t, { samplesPerLevel: 200 });
  const az = w.worstAzimuthTurns;
  const dir = az < 0.04 || az > 0.96 ? 'anterior' : Math.abs(az - 0.5) < 0.04 ? 'posterior' : `${(az * 12).toFixed(0)} o'clock`;
  line(
    `| \`${params.id}\` | ${w.level} | ${dir} | **${w.utilisation.toFixed(2)}** | ${w.foldRadiusMm.toFixed(0)} mm | ${w.radiusAtWorstMm.toFixed(0)} mm | ${probe.failures}/${probe.samples} | ${(ambiguousVolumeFraction(t) * 100).toFixed(2)}% |`,
  );
}
line();
line('`anat-adult-p50-split-sacrum` is the rejected design, kept to show the cost.');
line();

// ---------------------------------------------------------------------------
line('## 2. How many levels the fused sacrum should be');
line();
line('Worst utilisation (and the level it occurs at), by number of addressable');
line('sacral levels and by girth multiplier. Sacral axis taken from the chord in');
line('every row, to isolate this one variable.');
line();
line(`| sacral levels | ${GIRTHS.map((g) => `girth ${g.toFixed(2)}`).join(' | ')} |`);
line(`| --- | ${GIRTHS.map(() => '---').join(' | ')} |`);
for (const sacralLevels of [1, 2, 3, 4, 5]) {
  const cells = GIRTHS.map((radialScale) => {
    const t = buildAnatomicalBodyTemplate({
      ...ADULT_P50,
      id: `s${sacralLevels}-g${radialScale}`,
      sacralLevels,
      sacralTangentFraction: 0.5,
      radialScale,
    });
    const w = worstOf(auditBodyTemplate(t));
    const mark = w.utilisation >= 1 ? '**' : '';
    return `${mark}${w.utilisation.toFixed(2)}${mark} ${w.level}`;
  });
  line(`| ${sacralLevels} | ${cells.join(' | ')} |`);
}
line();
line('One level is better at every girth, and the ordering is monotone: cutting');
line('the fused sacrum into short levels is strictly worse, because each cut both');
line('shortens the chord and tightens the turn, and the sacral concavity faces');
line('the deep pelvis where there is a lot of tissue.');
line();

// ---------------------------------------------------------------------------
line('## 3. Where a collapsed sacral level takes its axis');
line();
line('With one sacral level, the binding site moves to the L5/S1 kink. How sharp');
line('that kink is depends on where along the sacral curve the level takes its');
line('axis direction: `0.0` follows the upper (S1) endplate, `0.5` is the chord of');
line('the whole sacrum.');
line();
line(`| sacral tangent fraction | ${GIRTHS.map((g) => `girth ${g.toFixed(2)}`).join(' | ')} |`);
line(`| --- | ${GIRTHS.map(() => '---').join(' | ')} |`);
for (const sacralTangentFraction of [0, 0.15, 0.25, 0.35, 0.5]) {
  const cells = GIRTHS.map((radialScale) => {
    const t = buildAnatomicalBodyTemplate({
      ...ADULT_P50,
      id: `f${sacralTangentFraction}-g${radialScale}`,
      sacralTangentFraction,
      radialScale,
    });
    const w = worstOf(auditBodyTemplate(t));
    const mark = w.utilisation >= 1 ? '**' : '';
    return `${mark}${w.utilisation.toFixed(2)}${mark} ${w.level}`;
  });
  line(`| ${sacralTangentFraction.toFixed(2)} | ${cells.join(' | ')} |`);
}
line();
line('The chord convention folds a large body; the endplate convention does not');
line('fold any body in this range. Note what the binding level becomes once the');
line('kink is relieved: a mid-lumbar level, posteriorly, at around half');
line('utilisation — which is as much margin as this frame can have.');
line();

// ---------------------------------------------------------------------------
line('## 4. Why the criterion has to be directional');
line();
line('The superseded criterion compared the *largest* radius at a level against');
line('the radius of curvature. That assumes the thickest tissue faces the concave');
line('side. In a trunk it faces the other way, because the spinal canal sits far');
line('posterior.');
line();
line('| template | worst-case verdict | exact verdict | observed failures | false alarms |');
line('| --- | --- | --- | --- | --- |');
for (const params of [...PRESETS, ADULT_P50_SPLIT_SACRUM]) {
  const t = buildAnatomicalBodyTemplate(params);
  const exact = auditBodyTemplate(t);
  const wc = auditBodyTemplateWorstCase(t);
  const probe = measureRoundTrip(t, { samplesPerLevel: 200 });
  const falseAlarms = wc.violations.filter((v) => !exact.violations.some((d) => d.level === v.level));
  line(
    `| \`${params.id}\` | ${wc.admissible ? 'pass' : 'FAIL ' + wc.violations.map((v) => v.level).join(',')} | ${exact.admissible ? 'pass' : 'FAIL ' + exact.violations.map((v) => v.level).join(',')} | ${probe.failures} | ${falseAlarms.length ? falseAlarms.map((v) => v.level).join(',') : '-'} |`,
  );
}
line();
line('The exact verdict matches the observed failures in every row. The worst-case');
line('verdict condemns five lumbar levels of an ordinary wide-waisted adult whose');
line('skin round-trips perfectly at every azimuth.');
line();

// ---------------------------------------------------------------------------
line('## 5. Requirements this puts on the asset pipeline');
line();
line('1. A body template realises **one** addressable sacral level, `S01`,');
line('   covering the whole fused sacrum. `S02`-`S05` stay reserved in the');
line('   grammar and absent from templates, which `locate()` already reports as');
line('   `homology: \'absent\'` rather than guessing.');
line('2. That level\'s axis direction follows the **upper sacral endplate**, not');
line('   the sacrum\'s chord.');
line('3. `auditBodyTemplate()` must pass, and its per-level table must be');
line('   published with the template. CI gates on it.');
line('4. Templates also run `measureRoundTrip()`; the audit is analytic, the');
line('   probe is the thing that cannot be fooled.');
line();
line('Requirements 1 and 2 cannot be retrofitted: changing the level set after');
line('addresses are issued invalidates them.');
line();
line('Caveat: the geometry here is typical adult proportions, good to perhaps');
line('10-15%, not a specific published cohort. It is sufficient for the questions');
line('answered above — which direction binds, and by how much margin — and it is');
line('no substitute for running the audit on the real mesh-derived template.');

process.stdout.write(out.join('\n') + '\n');
