/**
 * Regenerates docs/alc-1-admissibility.md.
 *
 *   node --experimental-strip-types test/admissibility.sweep.mjs > ../../docs/alc-1-admissibility.md
 *
 * Everything in that document comes from here, so no number in it is a claim
 * somebody typed by hand.
 */

import {
  auditBodyTemplate,
  auditBodyTemplateWorstCase,
  bodyLocalToMm,
  bodyMmToLocal,
  scanBodyTemplateFolds,
  spineGeometry,
} from '../src/index.ts';
import {
  ADULT_P50,
  FOLD_REGRESSIONS,
  PRESETS,
  ADULT_P50_SPLIT_SACRUM,
  buildAnatomicalBodyTemplate,
} from '../src/testing/anatomicalTemplates.ts';
import { measureRoundTrip } from '../src/testing/admissibilityProbe.ts';

/**
 * The committed regression fixture, taken from the ledger rather than rebuilt
 * here, so this document cannot describe a template the gate no longer watches.
 */
const CHORD_AXIS_LARGE = FOLD_REGRESSIONS
  .find((f) => f.params.id === 'anat-chord-axis-large').params;

const out = [];
const line = (s = '') => out.push(s);

const GIRTHS = [0.7, 0.85, 1.0, 1.15, 1.3, 1.45, 1.6, 1.75];

function roundTrips(t, level, u, az, r) {
  try {
    const mm = bodyLocalToMm(t, { level, u, t: az, r });
    const b = bodyMmToLocal(t, mm);
    let dt = Math.abs(b.local.t - az);
    dt = Math.min(dt, 1 - dt);
    return b.local.level === level && Math.abs(b.local.u - u) < 1e-6 && dt < 1e-6 && Math.abs(b.local.r - r) < 1e-6;
  } catch {
    return false;
  }
}

/** Volume-weighted fraction of the body where the frame is ambiguous. */
function ambiguousVolumeFraction(t) {
  const g = spineGeometry(t);
  let bad = 0;
  let all = 0;
  t.slabs.forEach((slab, i) => {
    const n = slab.surfaceRadiiMm.length;
    for (let a = 0; a < 48; a += 1) {
      const az = (a + 0.5) / 48;
      const rho = slab.surfaceRadiiMm[Math.round(az * n) % n];
      for (let k = 0; k < 24; k += 1) {
        const r = (k + 0.5) / 24;
        const w = r * rho * rho * g.lens[i];
        all += w;
        if (!roundTrips(t, slab.label, 0.5, az, r)) bad += w;
      }
    }
  });
  return bad / all;
}

const worstOf = (audit) => audit.levels.reduce((m, l) => (l.utilisation > m.utilisation ? l : m), audit.levels[0]);

line('# ALC-1 body template admissibility — measured report');
line();
line('Generated by `packages/alc/test/admissibility.sweep.mjs`. Every number below');
line('is computed, not asserted. Regenerate it whenever the frame or a template');
line('changes.');
line();
line('The `BD` frame is a tubular neighbourhood of the spinal curve, so it folds');
line('where the body is thicker than the distance at which a level\'s two bounding');
line('bisector planes meet. Beyond that fold two different addresses denote the');
line('same millimetre point, and `encode(locate(a))` stops returning `a`.');
line();
line('**Utilisation** below is `bodyRadius / foldRadius` at the worst azimuth of');
line('the worst level. Under 1 is admissible; 1 or more means part of the body is');
line('ambiguous.');
line();

// ---------------------------------------------------------------------------
line('## 1. The presets');
line();
line('| template | worst level | azimuth | utilisation | fold radius | body radius | round-trip failures | ambiguous volume |');
line('| --- | --- | --- | --- | --- | --- | --- | --- |');
for (const params of [...PRESETS, ADULT_P50_SPLIT_SACRUM]) {
  const t = buildAnatomicalBodyTemplate(params);
  const w = worstOf(auditBodyTemplate(t));
  const probe = measureRoundTrip(t, { samplesPerLevel: 200 });
  const az = w.worstAzimuthTurns;
  const dir = az < 0.04 || az > 0.96 ? 'anterior' : Math.abs(az - 0.5) < 0.04 ? 'posterior' : `${(az * 12).toFixed(0)} o'clock`;
  line(
    `| \`${params.id}\` | ${w.level} | ${dir} | **${w.utilisation.toFixed(2)}** | ${w.foldRadiusMm.toFixed(0)} mm | ${w.radiusAtWorstMm.toFixed(0)} mm | ${probe.failures}/${probe.samples} | ${(ambiguousVolumeFraction(t) * 100).toFixed(2)}% |`,
  );
}
line();
line('`anat-adult-p50-split-sacrum` is the rejected design, kept to show the cost.');
line();

// ---------------------------------------------------------------------------
line('## 2. How many levels the fused sacrum should be');
line();
line('Worst utilisation (and the level it occurs at), by number of addressable');
line('sacral levels and by girth multiplier. Sacral axis taken from the chord in');
line('every row, to isolate this one variable.');
line();
line(`| sacral levels | ${GIRTHS.map((g) => `girth ${g.toFixed(2)}`).join(' | ')} |`);
line(`| --- | ${GIRTHS.map(() => '---').join(' | ')} |`);
for (const sacralLevels of [1, 2, 3, 4, 5]) {
  const cells = GIRTHS.map((radialScale) => {
    const t = buildAnatomicalBodyTemplate({
      ...ADULT_P50,
      id: `s${sacralLevels}-g${radialScale}`,
      sacralLevels,
      sacralTangentFraction: 0.5,
      radialScale,
    });
    const w = worstOf(auditBodyTemplate(t));
    const mark = w.utilisation >= 1 ? '**' : '';
    return `${mark}${w.utilisation.toFixed(2)}${mark} ${w.level}`;
  });
  line(`| ${sacralLevels} | ${cells.join(' | ')} |`);
}
line();
line('One level is better at every girth, and the ordering is monotone: cutting');
line('the fused sacrum into short levels is strictly worse, because each cut both');
line('shortens the chord and tightens the turn, and the sacral concavity faces');
line('the deep pelvis where there is a lot of tissue.');
line();

// ---------------------------------------------------------------------------
line('## 3. Where a collapsed sacral level takes its axis');
line();
line('With one sacral level, the binding site moves to the L5/S1 kink. How sharp');
line('that kink is depends on where along the sacral curve the level takes its');
line('axis direction: `0.0` follows the upper (S1) endplate, `0.5` is the chord of');
line('the whole sacrum.');
line();
line(`| sacral tangent fraction | ${GIRTHS.map((g) => `girth ${g.toFixed(2)}`).join(' | ')} |`);
line(`| --- | ${GIRTHS.map(() => '---').join(' | ')} |`);
for (const sacralTangentFraction of [0, 0.15, 0.25, 0.35, 0.5]) {
  const cells = GIRTHS.map((radialScale) => {
    const t = buildAnatomicalBodyTemplate({
      ...ADULT_P50,
      id: `f${sacralTangentFraction}-g${radialScale}`,
      sacralTangentFraction,
      radialScale,
    });
    const w = worstOf(auditBodyTemplate(t));
    const mark = w.utilisation >= 1 ? '**' : '';
    return `${mark}${w.utilisation.toFixed(2)}${mark} ${w.level}`;
  });
  line(`| ${sacralTangentFraction.toFixed(2)} | ${cells.join(' | ')} |`);
}
line();
line('The chord convention folds a large body; the endplate convention does not');
line('fold any body in this range. Note what the binding level becomes once the');
line('kink is relieved: a mid-lumbar level, posteriorly, at around half');
line('utilisation — which is as much margin as this frame can have.');
line();

// ---------------------------------------------------------------------------
line('## 4. Why the criterion has to be directional');
line();
line('The superseded criterion compared the *largest* radius at a level against');
line('the radius of curvature. That assumes the thickest tissue faces the concave');
line('side. In a trunk it faces the other way, because the spinal canal sits far');
line('posterior.');
line();
// Both judgement columns are scored against the *measurement*, not against
// each other. Scoring "false alarms" as "condemned by the worst case, cleared
// by the exact criterion" silently treats the exact criterion as ground truth,
// which is how this section came to claim a match it did not have (QA-2): on
// the split sacrum it counted S01 and S05 as false alarms when both fold.
// Ground truth here is `scanBodyTemplateFolds`, which asks of every probed
// point how many levels claim it.
line('| template | worst-case verdict | exact verdict | observed failures | folding levels (measured) | worst-case false alarms | missed by the exact verdict |');
line('| --- | --- | --- | --- | --- | --- | --- |');
const directional = [];
for (const params of [...PRESETS, ADULT_P50_SPLIT_SACRUM]) {
  const t = buildAnatomicalBodyTemplate(params);
  const exact = auditBodyTemplate(t);
  const wc = auditBodyTemplateWorstCase(t);
  const probe = measureRoundTrip(t, { samplesPerLevel: 200 });
  const scan = scanBodyTemplateFolds(t);

  const order = t.slabs.map((s) => s.label);
  const byOrder = (a, b) => order.indexOf(a) - order.indexOf(b);
  const folds = new Map(scan.foldsByLevel.filter((f) => f.folds > 0).map((f) => [f.level, f.folds]));
  const folding = [...folds.keys()].sort(byOrder);
  const falseAlarms = wc.violations.map((v) => v.level).filter((l) => !folds.has(l)).sort(byOrder);
  const missed = folding.filter((l) => !exact.violations.some((d) => d.level === l));

  const verdict = (a) => (a.locallyAdmissible ? 'pass' : `FAIL ${a.violations.map((v) => v.level).join(',')}`);
  const list = (xs) => (xs.length ? xs.join(',') : '-');
  line(
    `| \`${params.id}\` | ${verdict(wc)} | ${verdict(exact)} | ${probe.failures} `
    + `| ${list(folding)} | ${list(falseAlarms)} | ${missed.length ? `**${missed.join(',')}**` : '-'} |`,
  );
  directional.push({
    id: params.id,
    missed: missed.map((l) => ({
      level: l,
      folds: folds.get(l),
      marginMm: exact.levels.find((x) => x.level === l)?.marginMm ?? NaN,
      utilisation: exact.levels.find((x) => x.level === l)?.utilisation ?? NaN,
    })),
    probed: scan.probed,
  });
}
line();
line('The worst-case verdict condemns five lumbar levels of an ordinary');
line('wide-waisted adult whose skin round-trips perfectly at every azimuth.');
line('That is the case for making the criterion directional, and it stands.');
line();

const missedRows = directional.filter((r) => r.missed.length > 0);
if (missedRows.length === 0) {
  line('In every row above, the exact verdict condemns every level the fold scan');
  line('finds folding. That is an observation about these templates and **not a');
  line('guarantee**: the criterion is per-level, and level assignment is a scan');
  line('over the whole column, so a non-adjacent level can claim a point the');
  line('criterion never looks at. Gate on `scanBodyTemplateFolds()` or');
  line('`measureRoundTrip()`, not on this column.');
} else {
  line('**The exact verdict is necessary, not sufficient, and the last column');
  line('shows it.** An earlier version of this section claimed "the exact verdict');
  line('matches the observed failures in every row". That was false on this');
  line("document's own data, and is QA-2 in `docs/alc-1-attack-report.md`. The");
  line('levels it clears that fold anyway:');
  line();
  for (const r of missedRows) {
    for (const m of r.missed) {
      line(
        `- \`${r.id}\` ${m.level}: cleared with **+${m.marginMm.toFixed(1)} mm** of `
        + `margin (utilisation ${m.utilisation.toFixed(3)}), and **${m.folds}** of its `
        + `own skin points, out of ${r.probed.toLocaleString('en-GB')} probed across the `
        + 'template, are claimed by a level other than their own.',
      );
    }
  }
  line();
  line('So those levels are not "false alarms" of the worst-case verdict — they');
  line('are levels the exact verdict wrongly *cleared*, which is the opposite');
  line('error and the dangerous direction.');
  line();
  line('The reason is structural, not a matter of tuning. This criterion asks');
  line("only whether a level's own two bounding bisector planes meet beyond its");
  line('skin, while level assignment scans the whole column, so a non-adjacent');
  line('level can claim a point the criterion never looks at. No per-level');
  line('condition can see that. Use the per-level margins to **localise** a fold');
  line('once one is known to exist, which is what they are genuinely good at,');
  line('and gate on `scanBodyTemplateFolds()` or `measureRoundTrip()`. The');
  line('library renamed the flag `locallyAdmissible` for this reason.');
}
line();

// ---------------------------------------------------------------------------
// QA-13 / DOG-18. Two claims used to be made about the per-level fold radius
// that this walk does not support: that the verdict matches the observed
// failures row for row (retired above, on DOG-10), and that the radius is a
// SHARP threshold rather than a one-sided bound. The second is retired here,
// with the measurement that retires it, because an asset pipeline reading a
// utilisation of 0.9 deserves to know what the 0.1 of margin does and does not
// buy. Walked on the knots of the level's own radius samples, not a round grid:
// the radii are interpolated between knots, so a local maximum can only sit on
// one and a coarser grid steps over the regime boundaries entirely.
line('### The per-level fold radius is a one-sided bound, not a threshold');
line();
line('Walking outward along each flagged level\'s worst azimuth, at mid-slab, and');
line('asking at every radius which level the point decodes back to:');
line();
line('| template | level | predicted fold `r` | first wrong answer | radii that answer correctly | first flagged `r` |');
line('| --- | --- | --- | --- | --- | --- |');
const RAY_STEPS = 2000;
const rays = [];
for (const params of [ADULT_P50_SPLIT_SACRUM, CHORD_AXIS_LARGE]) {
  const t = buildAnatomicalBodyTemplate(params);
  for (const v of auditBodyTemplate(t).violations) {
    const predicted = 1 / v.utilisation;
    let firstWrong = null;
    let firstFlagged = null;
    const bands = [];
    let open = null;
    for (let k = 1; k <= RAY_STEPS; k += 1) {
      const r = (k / RAY_STEPS) * 0.999;
      let res;
      try {
        res = bodyMmToLocal(t, bodyLocalToMm(t, { level: v.level, u: 0.5, t: v.worstAzimuthTurns, r }));
      } catch {
        continue;
      }
      const ok = res.local.level === v.level && Math.abs(res.local.r - r) < 1e-6;
      if (!ok && firstWrong === null) firstWrong = r;
      if (res.flags.folded && firstFlagged === null) firstFlagged = r;
      if (ok && open === null) open = r;
      if (!ok && open !== null) {
        bands.push([open, r]);
        open = null;
      }
    }
    if (open !== null) bands.push([open, 0.999]);
    const fmt = (x) => (x === null ? 'never' : x.toFixed(3));
    line(
      `| \`${params.id}\` | ${v.level} | ${predicted.toFixed(3)} | ${fmt(firstWrong)} `
      + `| ${bands.map(([a, b]) => `${a.toFixed(3)}–${b.toFixed(3)}`).join(', ')} `
      + `| ${fmt(firstFlagged)} |`,
    );
    rays.push({ id: params.id, level: v.level, predicted, firstWrong, firstFlagged, bands });
  }
}
line();
line('Three things to read off it, in order of how much they cost to get wrong.');
line();
{
  const early = rays
    .filter((r) => r.firstWrong !== null && r.firstWrong < r.predicted)
    .map((r) => ({ ...r, short: (r.predicted - r.firstWrong) / r.predicted }))
    .sort((a, b) => b.short - a.short);
  const broken = rays.filter((r) => r.bands.length > 1);
  line('1. **The prediction is a bound, and failure can start well inside it.** The');
  line('   predicted radius is where a level\'s own two bisector planes meet, so');
  line('   past it the level certainly cannot bracket its own point. Before it,');
  line('   nothing is promised: a level several places away can claim the point');
  line(`   first. Measured above, that happens on ${early.length} of the ${rays.length} rays,`);
  line(
    `   by up to **${(early.length ? early[0].short * 100 : 0).toFixed(1)}%** of the radius`
    + `${early.length ? ` (\`${early[0].id}\` ${early[0].level})` : ''}.`,
  );
  line('   An assertion of the form "safe just inside, folded just outside" is');
  line('   therefore ill-posed from the inner side, which is why');
  line('   `test/admissibility.test.ts` asserts only `firstFailure <= predicted`.');
  line('2. **Correctness is not monotone in radius.** A level can lose a point,');
  line('   then recover at a larger radius, then lose it again to a different');
  line('   level, so its correct radii are not one interval but several:');
  for (const r of broken) line(`   - \`${r.id}\` ${r.level}: ${r.bands.length} separate correct intervals.`);
  if (broken.length === 0) line('   - no row above, at this sampling.');
  line('   There is therefore no single radius at which a level stops working,');
  line('   and no utilisation figure that means "ambiguous beyond here".');
}
line('3. **The flag is not left behind by either of those.** The first flagged');
line('   radius is at or below the first wrong answer on every row, because');
line('   `bodyMmToLocal` no longer asks how many levels claim the point — which');
line('   is a question with gaps — but whether any *other* level has an in-body');
line('   address for it, which is the fold itself. Both halves of spec §4\'s');
line('   "wedge on the convex side and gap on the concave side" answer it.');
line('   (QA-13; the displacement half used to be silent.)');
line();
line('None of this weakens the gate. The gate is `scanBodyTemplateFolds()` being');
line('sound, which is a statement about every probed point rather than about a');
line('radius, and it is unaffected by where along a ray the failure starts.');
line();

// ---------------------------------------------------------------------------
line('## 5. Requirements this puts on the asset pipeline');
line();
line('1. A body template realises **one** addressable sacral level, `S01`,');
line('   covering the whole fused sacrum. `S02`-`S05` stay reserved in the');
line('   grammar and absent from templates, which `locate()` already reports as');
line('   `homology: \'absent\'` rather than guessing.');
line('2. That level\'s axis direction follows the **upper sacral endplate**, not');
line('   the sacrum\'s chord.');
line('3. `scanBodyTemplateFolds()` must find the template **sound**. That is the');
line('   gate. `auditBodyTemplate()` must also pass and its per-level table must');
line('   be published with the template, but per §4 that is a necessary');
line('   condition only, so it cannot be the gate on its own.');
line('4. Templates also run `measureRoundTrip()`; the audit is analytic, the');
line('   probe is the thing that cannot be fooled.');
line();
line('Requirements 1 and 2 cannot be retrofitted: changing the level set after');
line('addresses are issued invalidates them.');
line();
line('Caveat: the geometry here is typical adult proportions, good to perhaps');
line('10-15%, not a specific published cohort. It is sufficient for the questions');
line('answered above — which direction binds, and by how much margin — and it is');
line('no substitute for running the audit on the real mesh-derived template.');

process.stdout.write(out.join('\n') + '\n');
